"""
Shared type definitions for all graphs.
========================================

These TypedDicts are used across multiple graph state definitions.
Import them from here rather than redefining in each graph's state.py.
"""

from typing import TypedDict, Literal


class CodeFile(TypedDict):
    """Represents a code file generated by agents."""
    path: str
    content: str
    language: str


class UserStory(TypedDict):
    """Represents a user story from the analyst."""
    id: str
    title: str
    description: str
    acceptance_criteria: list[str]
    priority: Literal["high", "medium", "low"]


class ArchitectureDecision(TypedDict):
    """Represents an architectural decision."""
    component: str
    technology: str
    rationale: str
