"""
Pydantic models for structured LLM output.
============================================

Each agent method that parses an LLM response has a corresponding
schema here.  Used with ``BaseAgent._invoke_structured()`` which
tries ``llm.with_structured_output()`` first and falls back to
string parsing when the model doesn't support it.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


# ── Analyst ──────────────────────────────────────────────────────

class AnalystResponse(BaseModel):
    """Output of the analyst's requirements gathering."""
    needs_clarification: bool = Field(
        False, description="True if the analyst needs more info from the user")
    clarification_question: str | None = Field(
        None, description="Question to ask the user (if needs_clarification)")
    requirements: list[str] = Field(
        default_factory=list, description="List of extracted requirements")


# ── Architect ────────────────────────────────────────────────────

class ArchitectDesignResponse(BaseModel):
    """Output of the architect's design phase."""
    design: str = Field(description="Full architecture description in markdown")
    tech_stack: list[str] = Field(
        default_factory=list, description="Technologies chosen (e.g. Python, React)")


class ArchitectReviewResponse(BaseModel):
    """Output of the architect's QA escalation review."""
    approved: bool = Field(description="Whether the code is approved")
    critical_issues: list[str] = Field(
        default_factory=list, description="Critical issues that must be fixed")


# ── Reviewer ─────────────────────────────────────────────────────

class ReviewerResponse(BaseModel):
    """Output of the reviewer's code review."""
    approved: bool = Field(description="Whether the code passes review")
    issues_found: list[str] = Field(
        default_factory=list, description="Critical/major issues found")
    review_comments: list[str] = Field(
        default_factory=list, description="All review comments")


class ReviewerVerifyResponse(BaseModel):
    """Output of the reviewer's fix verification."""
    all_fixed: bool = Field(description="Whether all issues have been fixed")


# ── Security ─────────────────────────────────────────────────────

class SecurityReviewResponse(BaseModel):
    """Output of the security agent's review."""
    risk_level: str = Field(
        "LOW", description="Overall risk: CRITICAL, HIGH, MEDIUM, LOW")
    critical: list[str] = Field(
        default_factory=list, description="Critical security findings")
    warnings: list[str] = Field(
        default_factory=list, description="Security warnings")
    info: list[str] = Field(
        default_factory=list, description="Informational notes")
    summary: str = Field("", description="Brief summary of the review")


# ── QA (shared across sandbox/browser/exploration) ───────────────

class QAVerdictResponse(BaseModel):
    """Verdict from QA analysis (sandbox, browser, or exploration)."""
    approved: bool = Field(description="True if tests pass (PASS verdict)")
    issues: list[str] = Field(
        default_factory=list, description="Issues / failures found")
    defects: list[QADefect] = Field(
        default_factory=list, description="Visual/functional defects")


class QADefect(BaseModel):
    """A single defect found during QA."""
    description: str = Field(description="What the defect is")
    severity: str = Field("medium", description="Severity: critical, high, medium, low")


# Fix forward reference
QAVerdictResponse.model_rebuild()


# ── Developer ────────────────────────────────────────────────────

class DeveloperFileOutput(BaseModel):
    """A single code file generated by the developer."""
    path: str = Field(description="File path (e.g. src/main.py)")
    language: str = Field(description="Programming language")
    content: str = Field(description="File content")


class DeveloperResponse(BaseModel):
    """Output of the developer's implementation."""
    files: list[DeveloperFileOutput] = Field(
        default_factory=list, description="Generated code files")


# ── Exploration plan ─────────────────────────────────────────────

class ExplorationStep(BaseModel):
    """A single step in the QA exploration plan."""
    name: str = Field(description="Step name")
    action: str = Field(description="What to do")
    expected: str = Field("", description="Expected outcome")


class ExplorationPlanResponse(BaseModel):
    """QA exploration test plan."""
    steps: list[ExplorationStep] = Field(
        default_factory=list, description="Ordered list of exploration steps")


# ── DevOps ──────────────────────────────────────────────────────

class InfraFileOutput(BaseModel):
    """A single infrastructure file generated by the DevOps agent."""
    path: str = Field(description="File path (e.g. Dockerfile, docker-compose.prod.yml)")
    content: str = Field(description="File content")


class DevOpsResponse(BaseModel):
    """Output of the DevOps agent's infrastructure generation."""
    infra_files: list[InfraFileOutput] = Field(
        default_factory=list, description="Generated infrastructure files")
    deploy_url: str = Field("", description="Expected deployment URL")
    env_vars_needed: list[str] = Field(
        default_factory=list, description="Environment variables required on deploy VPS")
    notes: str = Field("", description="Human-readable deployment notes")
