"""
DevTeam State Definition
========================

Defines ``DevTeamState`` — the shared TypedDict passed between all
LangGraph nodes in the dev-team workflow.

Key sections:
  - **Input** — task, repository, context (provided by the user)
  - **Agent outputs** — requirements, architecture, code_files, etc.
  - **Conversation** — LangGraph message history (auto-accumulated)
  - **Control flow** — current_agent, needs_clarification, qa counters
"""

from typing import TypedDict, Annotated, Literal
try:
    from typing import NotRequired  # Python 3.11+
except ImportError:
    from typing_extensions import NotRequired  # Python 3.9-3.10

from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class CodeFile(TypedDict):
    """Represents a code file generated by agents."""
    path: str
    content: str
    language: str


class UserStory(TypedDict):
    """Represents a user story from the analyst."""
    id: str
    title: str
    description: str
    acceptance_criteria: list[str]
    priority: Literal["high", "medium", "low"]


class ArchitectureDecision(TypedDict):
    """Represents an architectural decision."""
    component: str
    technology: str
    rationale: str


class DevTeamState(TypedDict):
    """
    Main state for the development team graph.
    
    This state is passed between all agents and accumulates
    the work products of each stage.
    """
    
    # === Input ===
    task: str                                    # Original task description
    repository: NotRequired[str]                 # Target GitHub repository URL
    context: NotRequired[str]                    # Additional context/requirements
    
    # === Analyst Output ===
    requirements: list[str]                      # Extracted requirements
    user_stories: list[UserStory]                # User stories
    
    # === Architect Output ===
    architecture: dict                           # Architecture specification
    tech_stack: list[str]                        # Chosen technologies
    architecture_decisions: list[ArchitectureDecision]
    
    # === Developer Output ===
    code_files: list[CodeFile]                   # Generated code files
    implementation_notes: str                    # Notes about implementation
    
    # === QA Output ===
    review_comments: list[str]                   # Code review feedback
    test_results: dict                           # Test execution results
    issues_found: list[str]                      # Issues to fix
    
    # === Final Output ===
    pr_url: NotRequired[str]                     # Created PR URL
    commit_sha: NotRequired[str]                 # Commit SHA
    summary: str                                 # Final summary
    
    # === Conversation ===
    messages: Annotated[list[BaseMessage], add_messages]
    
    # === Control Flow ===
    current_agent: str                           # Currently active agent
    next_agent: NotRequired[str]                 # Next agent to invoke
    
    # === Human-in-the-Loop ===
    needs_clarification: bool                    # Flag for HITL
    clarification_question: NotRequired[str]     # Question for user
    clarification_context: NotRequired[str]      # Context for the question
    clarification_response: NotRequired[str]     # User's response
    
    # === Iteration control ===
    qa_iteration_count: int                      # Dev↔QA loop counter (reset after architect escalation)
    architect_escalated: bool                    # True after first architect escalation in Dev↔QA loop

    # === Error Handling ===
    error: NotRequired[str]                      # Error message if any
    retry_count: int                             # Number of retries


def create_initial_state(
    task: str,
    repository: str | None = None,
    context: str | None = None
) -> DevTeamState:
    """
    Create an initial state for a new task.
    
    Args:
        task: The task description
        repository: Optional GitHub repository URL
        context: Optional additional context
        
    Returns:
        Initialized DevTeamState
    """
    # Build state dict, only including NotRequired fields if they have values
    state: dict = {
        # Required input
        "task": task,
        
        # Required outputs (empty by default)
        "requirements": [],
        "user_stories": [],
        "architecture": {},
        "tech_stack": [],
        "architecture_decisions": [],
        "code_files": [],
        "implementation_notes": "",
        "review_comments": [],
        "test_results": {},
        "issues_found": [],
        "summary": "",
        
        # Conversation
        "messages": [],
        
        # Control
        "current_agent": "pm",
        
        # HITL
        "needs_clarification": False,
        
        # Iteration control
        "qa_iteration_count": 0,
        "architect_escalated": False,

        # Error handling
        "retry_count": 0,
    }
    
    # Only add NotRequired fields if they have values
    if repository is not None:
        state["repository"] = repository
    if context is not None:
        state["context"] = context
    
    return DevTeamState(**state)
